<<<<<<< HEAD
name: Labs Test

on: push

jobs:
  hello:
    runs-on: ubuntu-20.04
    name: Hello
    steps:
      - uses: actions/checkout@v2
      - run: echo "Hello"
  # lab3:
  #   runs-on: ubuntu-20.04
  #   name: Lab №3
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Setup node
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 10
  #     - run: npm install
  #     - run: npm run test-lab-3
  # lab4:
  #   runs-on: ubuntu-20.04
  #   needs: [lab3]
  #   name: Lab №4
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Setup node
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 10
  #     - run: npm install
  #     - run: npm run test-lab-4
=======
name: Labs Test

on: push

jobs:
  hello:
    runs-on: ubuntu-20.04
    name: Hello
    steps:
      - uses: actions/checkout@v2
      - run: echo "Hello"
  lab3:
    runs-on: ubuntu-20.04
    name: Lab №3
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
      - run: npm run test-lab-3
  # lab4:
  #   runs-on: ubuntu-20.04
  #   needs: [lab3]
  #   name: Lab №4
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Setup node
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 10
  #     - run: npm install
  #     - run: npm run test-lab-4
>>>>>>> 0471e28129b1224699124949c150a16736eb0dff
